courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/chat/urls.py
import os
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('syntax', TemplateView.as_view(template_name='chat/syntax.html'), 
        name='syntax'),
    path('jsonfun', views.jsonfun, name='jsonfun'),

    path('talk', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='myarts'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='all'),
    path('article/<int:pk>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/create', 
        views.ArticleCreateView.as_view(success_url=reverse_lazy('myarts:all')), name='article_create'),
    path('article/<int:pk>/update', 
        views.ArticleUpdateView.as_view(success_url=reverse_lazy('myarts:all')), name='article_update'),
    path('article/<int:pk>/delete', 
        views.ArticleDeleteView.as_view(success_url=reverse_lazy('myarts:all')), name='article_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings


class Article(models.Model):
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/views.py
from myarts.models import Article
from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView


class ArticleListView(OwnerListView):
    model = Article
    # By convention:
    # template_name = "myarts/article_list.html"


class ArticleDetailView(OwnerDetailView):
    model = Article


class ArticleCreateView(OwnerCreateView):
    model = Article
    fields = ['title', 'text']


class ArticleUpdateView(OwnerUpdateView):
    model = Article
    fields = ['title', 'text']


class ArticleDeleteView(OwnerDeleteView):
    model = Article

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/templates/myarts/article_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the article: {{ article }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/templates/myarts/article_detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ article.updated_at|naturaltime }})
{% if article.owner == user %}
<a href="{% url 'myarts:article_update' article.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'myarts:article_delete' article.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ article.title }}</h1>
<p>
{{ article.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'myarts:all' %}">All articles</a>
</p>
{% endblock %}

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/templates/myarts/article_form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'myarts:all' %}';return false;">
  </form>
</p>
{% endblock %}

courses/backend/django-for-everybody/Web Application Technologies and Django/resources/dj4e-samples/myarts/templates/myarts/article_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Articles</h1>
<p>
{% if article_list %}
<ul>
  {% for article in article_list %}
    <li>
        <a href="{% url 'myarts:article_detail'  article.id %}">{{ article.title }}</a>
        {% if article.owner == user %}
        (<a href="{% url 'myarts:article_update' article.id %}">Edit</a> |
        <a href="{% url 'myarts:article_delete' article.id %}">Delete</a>)
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no articles in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'myarts:article_create' %}">Add an Article</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'myarts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'myarts:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}